#!/bin/bash
/usr/bin/mvn $* | sed \
  -e 's_\(Failures: [1-9][0-9]*\)_\o033[1;31m\1\o033[0m_g' \
  -e 's_\(Errors: [1-9][0-9]*\)_\o033[1;31m\1\o033[0m_g' \
  -e 's_\(Skipped: [1-9][0-9]*\)_\o033[1;33m\1\o033[0m_g' \
  -e 's_\(\[WARN\].*\)_\o033[1;33m\1\o033[0m_g' \
  -e 's_\(\[WARNING\].*\)_\o033[1;33m\1\o033[0m_g' \
  -e 's_\(\[ERROR\].*\)_\o033[1;31m\1\o033[0m_g' \
  -e 's_\(\[INFO] BUILD SUCCESSFUL\)_\o033[1;32m\1\o033[0m_g'

